baseURL = "http://dev.albopop.it/"
title = "AlboPOP"
theme = "albopop"
copyright = "CC-BY 4.0 Ondata"
languageCode = "it"
defaultContentLanguage = "it"
[params]
    mainSections = ["post"]
    [params.colors]
        red = "#ff0000"
        lred = "#ffb8b8"
        blue = "#266ff0"
        lblue = "#cae5f8"
        dblue = "#2a9ced"
        orange = "#fe9705"
        green = "#3ac430"
        yellow = "#0569ff"
        black = "#021b44"
        white = "#ffffff"
        lwhite = "#f9f9f9"
        grey = "#ededed"
        twitter = "#55acee"
        facebook = "#4465b8"
        telegram = "#2da4d7"
        rss = "#ff9845"
    [params.fonts]
        title = "'Montserrat', sans-serif"
        paragraph = "'Georgia', serif"
        