baseURL = "http://dev.albopop.it/"
title = "AlboPOP"
theme = "albopop"
copyright = "CC-BY 4.0 Ondata"
languageCode = "it"
defaultContentLanguage = "it"

[menu]
  [[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/ondata/albopopTwoDotZero"
    weight = -100

[params]
    mainSections = ["post"]
    [params.colors]
        red = "#ff0000"
        lred = "#ffb8b8"
        blue = "#266ff0"
        lblue = "#cae5f8"
        dblue = "#2a9ced"
        orange = "#fe9705"
        green = "#3ac430"
        yellow = "#0569ff"
        black = "#021b44"
        white = "#ffffff"
        lwhite = "#f9f9f9"
        grey = "#ededed"
        twitter = "#55acee"
        facebook = "#4465b8"
        telegram = "#2da4d7"
        rss = "#ff9845"
    [params.fonts]
        title = "'Montserrat', sans-serif"
        paragraph = "'Georgia', serif"
    [params.labels]
        [params.labels.accessible]
            name = "accessible"
            title = "Accessibile"
            description = "Per classificare chi pubblica scansioni di PDF"
        [params.labels.standard]
            name = "standard"
            title = "Standard"
            description = "Per chi è compliant specifiche alboPOP"
        [params.labels.official]
            name = "official"
            title = "Ufficiale"
            description = "Per chi ha emesso una delibera ufficiale"

[permalinks]
  altrepa = "/altrepa/:filename"
  comune = "/comune/:filename"

[outputs]
    page = ["HTML","JSON"]